
import React, { createContext } from "react";
import ConA from "./ConA";
//component name should be start with uppercase
const App = () => {

    const Firstname = createContext();             //creating a component with help of createcontext() method which use to pass data in another component without using prop
    const Lastname = createContext();

    return (
        <>
            <Firstname.Provider value={"abhi"}>
                <Lastname.Provider value={"hat"}>
                    <ConA></ConA>                            
                </Lastname.Provider>
            </Firstname.Provider>
        </>);
}

export default App;
export { Firstname, Lastname };




//always write other components inside the component generated by createcontext  

//sending data using context api become messy if we want to send multiple data but using useContext hook it will become easier it gives same functionality as context api but receiving end it create code less messy if multiple data is to send
